modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
logoFile = "assets/gaisoumod/icon.png"
#credits="Thanks for this example mod goes to Java"
authors = "Pitan"
description = '''

'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "mcpitanlib"
mandatory = true
versionRange = "[2.3.0,)"
ordering = "BEFORE"
side = "BOTH"

